### ISSUE TITLE
Stability issues with the R9 Nano

### ISSUE THREAD

**Issue by mjdecour** [Optiminer/OptiminerZcash#1]
Rigs are failing after 30-120 mins using optiminer v4.  Rolled back to optiminer v3.4 and the rigs are stable again.

**Comment by mjdecour** [comment]
![img_0870](https://cloud.githubusercontent.com/assets/507224/20643970/b27564ba-b3db-11e6-9134-1e4609612edb.JPG)

**Comment by Optiminer** [comment]
It is probably an issue with risers. Try replacing them by better ones. See zcash forum for choosing which ones.

**Comment by mjdecour** [comment]
@optiminer this is not an issue with my risers as I don't have problems running other mining software. Also rolling back to v3.4 proves to be much more stable.

**Comment by traycho** [comment]
I have some issues with 5 cards one of them is just stopping after start  (511+ using output of sensors) after start of miner, what could be the problem here ?

**Comment by Optiminer** [comment]
Try latest version.
