### ISSUE TITLE
OptiminerZ Windows v0.3.1 (Beta):ERROR [default] OpenCL error

### ISSUE THREAD

**Issue by RockZhou8** [Optiminer/OptiminerZcash#13]
$ ./optiminer-zcash -s eu1-zcash.flypool.org:3333 -u t1Yszagk1jBjdyPfs2GxXx1GWcfn6fdTuFJ.example -p password
2016-11-14 00:39:32,396 INFO  [default] Optiminer/Zcash 0.3.1 (C) Optiminer 2016
2016-11-14 00:39:32,733 ERROR [default] OpenCL error: cl::Context::Context() (-1)

**Comment by Optiminer** [comment]
This means it failed to init the opencl context. Do you have opencl installed? Do you need to specify a different platform? You can use clinfo to list your platforms and devices: https://github.com/Oblomov/clinfo
