### ISSUE TITLE
HD 7000 problems

### ISSUE THREAD

**Issue by EvgenRad81** [Optiminer/OptiminerZcash#13]
I have some HD 7000 series videocards. Trying to launch v.1.0.1 on it.

Farm 1 - Ubuntu 14.04+fgrlx (3x7950+1x280x.)
Miner crashes on start. 0.6.0 works fine.

Farm 2 - Ubuntu 14.04+fgrlx (2x7870)
Miner works only with 1 GPU. If trying to start on 2 GPUs, miner crashes. 0.6.0 works fine.

Farm 3 - Ubuntu 14.04+fgrlx (5x270+1x7870)
Miner starts, but after few time, 7870 stucks. 0.6.0 works fine.

Tuning intensity - no luck.
All other farms without HD 7000 series GPU, works fine. I have 270,280,470,

**Comment by Optiminer** [comment]
Please try with 1.3.2.
