### ISSUE TITLE
Windows: Failed to find bin/X-base.bin

### ISSUE THREAD

**Issue by rbrtio** [Optiminer/OptiminerZcash#14]
It appears the files in the bin directory of the Windows zip file are named wrong.

They are shipped as X_base.bin and the application is looking for X-base.bin and the same applies to all of the other files.

**Comment by Optiminer** [comment]
Have you tried renaming them?

**Comment by rbrtio** [comment]
Yes, that gets me past this issue and onto the can't connect to the pool issue.  :-)

**Comment by rbrtio** [comment]
This issue is resolved in 0.3.1a release.
