### ISSUE TITLE
System freezes after some time

### ISSUE THREAD

**Issue by WoK-E** [Optiminer/OptiminerZcash#18]
This is a fresh installation
Ubuntu 16.04.1 Server
amdgpu-pro 16.30
ASROCK FM2A58+ m/b, AMD A6-7400K
4 x RX470 w/ 4GB, 1 x RX480 w/ 8GB

optiminer runs on 5 GPUs, but not on the embedded R5 GPU

Works fine for about an hour, and then system freezes.
I have ots of GPU faults when the system is running (VM_CONTEXT1_PROTECTION_FAULT_ADDR is always 0x04102F3F and the _STATUS is 0x0?0C4001 [?=0,2,4,6,8])

Is there any way to provide you with more info as to why the system crashes? Is there a debugging switch?

I have 2 more rigs with R9380 and R9380X GPUs that run fine.

**Comment by rbrtio** [comment]
Several of us seem to be having issues with RX series cards with similar messages.  See #8

**Comment by mifa** [comment]
Same here on r9 390, it freezes after about 10 hours

**Comment by WoK-E** [comment]
No problem since 0.3.2
