### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by randrei** [Optiminer/OptiminerZcash#2]
Miner is unable to start. I'm running 5 x rx 470 8gb on Ubuntu 16.04 (amdgpu pro).

Log file:
2016-11-12 13:43:32,316 INFO  [default] Using device 'Ellesmere'
2016-11-12 13:43:32,317 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
2016-11-12 13:43:32,317 WARN  [default] Aborting application. Reason: Fatal log at [../logging/easylogging++.h:5627]

**Comment by Optiminer** [comment]
Which graphic driver are you using? Strangely enough, I have exactly the same system (Ubuntu 16.04.1) with rx 470 running (it's a 4gb card though).

**Comment by randrei** [comment]
I'm running amdgpu pro 16.40. The cards are modded (mem overclock, undervolt), but they are running fine with silentarmy

**Comment by padrino121** [comment]
It would be appropriate to say it works on 16.04 only, or at least note the speicifc libc versions, does not run for example on Ubuntu 14.04

**Comment by randrei** [comment]
Ok, I've removed all cards, then plugged 1 directly to mobo, reflashed to stock vbios and the miner still crashes on startup. Maybe this could be an OpenCl problem?

**Comment by randrei** [comment]
@Optiminer any ideas?

**Comment by Optiminer** [comment]
Try with latest version.

**Comment by randrei** [comment]
Already did, same issue

**Comment by Optiminer** [comment]
So, you say it crashes on every startup? Seems you are the only one having this issue so far. You could try to run it with gdb and give me the stack trace of the crash if you feel adventurous.

**Comment by randrei** [comment]
There were also some users on the ZCash forum reporting about a crash. I'm not familiar with gdb. I've tried running optiminer from it, and doing a backtrace.
(gdb) run -s eu1-zcash.flypool.org:3333 -u t1fcm31Y6mMhfe6o4tH2f8KqgDYiLCcCwmH
Starting program: /home/mimi/optiminer/optiminer-zcash/optiminer-zcash -s eu1-zcash.flypool.org:3333 -u t1fcm31Y6mMhfe6o4tH2f8KqgDYiLCcCwmH
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2016-11-13 21:56:54,412 INFO  [default] Optiminer/Zcash 0.3.1 (C) Optiminer 2016
[New Thread 0x7ffff693c700 (LWP 17273)]
[New Thread 0x7ffff613b700 (LWP 17274)]
2016-11-13 21:56:54,516 INFO  [stratum] Extranonce is 63bf71a037
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
2016-11-13 21:56:54,559 INFO  [stratum] Connected to eu1-zcash.flypool.org:3333
2016-11-13 21:56:54,559 INFO  [stratum] Mining target is 004189374bc6a7ef9db22d0e5604189374bc6a7ef9db22d0e5604189374bc6a7
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
pci id for fd 18: 1002:67df, driver (null)
[New Thread 0x7fffe0bb4700 (LWP 17275)]
[New Thread 0x7fffe03b3700 (LWP 17276)]
[Thread 0x7fffe03b3700 (LWP 17276) exited]
[Thread 0x7fffe0bb4700 (LWP 17275) exited]
[New Thread 0x7fffe80a0700 (LWP 17277)]
2016-11-13 21:56:54,655 INFO  [GPU0] Using device 'Ellesmere

Thread 1 "optiminer-zcash" received signal SIGSEGV, Segmentation fault.
0x0000000000c4bfd0 in ?? ()
(gdb) stacktrace
Undefined command: "stacktrace".  Try "help".
(gdb) backtrace
#0  0x0000000000c4bfd0 in ?? ()
#1  0x00007fffea18aa8a in ?? () from /usr/lib64/OpenCL/vendors/amd/libamdocl12cl64.so
#2  0x00007fffea18d3da in ?? () from /usr/lib64/OpenCL/vendors/amd/libamdocl12cl64.so
#3  0x00007fffea5168ec in ?? () from /usr/lib64/OpenCL/vendors/amd/libamdocl12cl64.so
#4  0x00007fffec91a5c1 in ?? () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#5  0x00007fffec8fa025 in clCreateProgramWithBinary () from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
#6  0x0000000000440b7c in ?? ()
#7  0x000000000043f261 in ?? ()
#8  0x00000000004401c0 in ?? ()
#9  0x000000000041d2f5 in ?? ()
#10 0x000000000041ec8e in ?? ()
#11 0x0000000000430622 in ?? ()
#12 0x000000000042411e in ?? ()
#13 0x00000000004255ef in ?? ()
#14 0x00000000004057b8 in ?? ()
#15 0x00007ffff6d69830 in __libc_start_main (main=0x405600, argc=5, argv=0x7fffffffe498, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe488) at ../csu/libc-start.c:291
#16 0x0000000000406029 in ?? ()
(gdb) 

Is this helpful ?

**Comment by randrei** [comment]
Well, I ran out of options and reinstalled the rig: Ubuntu, amdgpu-pro + opencl and now it works. The thing that let me to this was that clinfo was seg faulting after printing all output.
