### ISSUE TITLE
Add an option of writing logs to specified file

### ISSUE THREAD

**Issue by osnwt** [Optiminer/OptiminerZcash#22]
Version 0.3.1 does not write log files anymore. It was used by me to watch log updates by the system watchdog and restart it if no changes for more than some time. Unfortunately, there is no more logs (why?). I realise that I can redirect stdout to a file, but a better solution will be some optional parameter with log file name (say, -l /path/filename.log). If it is missing - no log written, if it exists - write log to that file. -L could be used to control file truncation before start (-l to append, -L to truncate).

**Comment by Optiminer** [comment]
Log file choosing is implemented. I am not going to do the truncate for now. Just rm the file before restarting the log in a bash script if needed.
