### ISSUE TITLE
Stability issues #1

### ISSUE THREAD

**Issue by meister-t** [Optiminer/OptiminerZcash#24]
My name is Meister-T and I work with the PiMP Testing/Support Team. We have filed this issue based on our testing and/or reports from our customers. Thank you very much for your work toward our mutual goal of making easy and effective tools for miners. We are bringing this issue to light because it is affecting a lot of users and we need your help.

We reproduced this issue on PiMP v2.0, which is currently based on Ubuntu 16.04 with AMDGPU-PRO 16.40 Drivers. The OS packages have been fully updated to today’s date, and we have followed the instructions on your git. 

We are using your software Optiminer v1.3.2, and are facing the following issue:

With a setup running 2x RX480 and a higher Memory Clock which in this case is 2200 MHz which is 200 MHz more than the stock clocks, the miner pushes out either the first or the 2nd GPU. When this happens and after trying to restart the miner it seems to freeze and not starting to mine anymore. Putting the GPUs back to their stock clocks of 2000 MHz though and performing a duration-test of 24 hours the problem seems non-existent.

Another report has also reveiled that the miner crashes within 10-15 minutes after starting it on the modded 2200 MHz clocks.

Meister-T
PiMP Testing/Support Team
Need help with PiMP? Join #PiMP Livechat on Freenode for active support and discussion!

**Comment by Optiminer** [comment]
This just means that the hardware cannot handle the 2200 Mhz memory clock. I do not think there is much I can do from the software side.

**Comment by bpvarsity** [comment]
2200 Mhz works just fine with other miners. I run many 480's at 2200

**Comment by Optiminer** [comment]
That it works with other miners does not mean anything. Optiminer has a higher hash rate at the same clock, so it utilizes the memory more.

**Comment by bpvarsity** [comment]
Guess we will see once another miner software gets the same hash rate. Then we know if it really is a "hardware" issue.

**Comment by jstefanop** [comment]
@bpvarsity lol so your saying when you overclock past stock clocks the miner crashes, and when you revert to stock it does not., but thats NOT a hardware issue? Thats the definition of a hardware fault. That has nothing to do with the miner, your just pushing the clocks past what they can handle.
