### ISSUE TITLE
Miner stopping and starting every few minutes on Nicehash

### ISSUE THREAD

**Issue by scavern** [Optiminer/OptiminerZcash#24]
Mining to equihash.eu.nicehash.com it appears that the miner stops and starts every few minutes. The longest I have seen it connected. There are no connectivity issues on my side.

**Comment by elgi76** [comment]
i think nicehash isn't a real pool, it's a rental service. your hashrate change sometime of pool, of customer, etc...

**Comment by scavern** [comment]
I know the hashrate varies, but every other miner I have used doesn't appear to come to a complete standstill after a few minutes. Either way I will keep on monitoring it.
