### ISSUE TITLE
Stability issues #2

### ISSUE THREAD

**Issue by meister-t** [Optiminer/OptiminerZcash#26]
My name is Meister-T and I work with the PiMP Testing/Support Team. We have filed this issue based on our testing. 
Thank you very much for the update that you made and we are glad to deploy for all PiMPs. 
However the issues that were in your previous version are not resolved nor replied to https://github.com/Optiminer/OptiminerZcash/issues/24. 

We have done tests with the stock clocks enabled.
Hasrate on stock clock after a 2 hour dura (our minimum dura test time) : hashrate went from 520 sols/s to 535 sols/s on 2 cards.
 
If we can assist with testing or the development. Feel free to contact us on irc on our live chat and tell us what we can do to help you.

Meister-T
PiMP Testing/Support Team
Need help with PiMP? Join #PiMP Livechat on Freenode for active support and discussion!

**Comment by Optiminer** [comment]
Let's continue discussion on #24.
