### ISSUE TITLE
miner spontaneously stops

### ISSUE THREAD

**Issue by nerdralph** [Optiminer/OptiminerZcash#27]
```
2016-11-14 10:31:42,120 INFO  [GPU0]  79.0 I/s 170.0 S/s (1s) 80.4 I/s 151.0 S/s (1m) 80.4 I/s 150.4 S/s (1h)
2016-11-14 10:31:43,112 INFO  [GPU2]  48.0 I/s 79.0 S/s (1s) 48.8 I/s 90.3 S/s (1m) 48.8 I/s 91.4 S/s (1h)

```

Ubuntu 14.04/fglrx running 0.3.1.  No errors or core dump.  Resumes fine after restarting optiminer.

**Comment by scavern** [comment]
Exact same issue I have. Has happened on all my rigs  R9 380, R9 280, 7960, 7970.

**Comment by Optiminer** [comment]
So, the miner just exits?

**Comment by DavBE** [comment]
Same issue here, running miner on 4 rigs, happened 2 or 3 times. Miner just exits, no error. A workaround would be running it in a loop inside a script. and that would also fix the reconnect issues. Hopefully I'll post one when I have time to write it.

**Comment by scavern** [comment]
yep, just exits. my workaround was just to create a script which fires off in cron every 5 minutes to check if the process is running and start it if it isn't.

**Comment by DavBE** [comment]
Something like that should do the trick :
```
#!/bin/bash

while true;
do

./optiminer-zcash -u username -p z -s stratum:port

done
```

**Comment by Optiminer** [comment]
Does it still happen with the latest version?

**Comment by nerdralph** [comment]
0.3.2 seems to have fixed this for me.
