### ISSUE TITLE
Doesn't run - libOpenCL.so.1 cannot open object - Invalid instructions.. :(

### ISSUE THREAD

**Issue by alexellis** [Optiminer/OptiminerZcash#30]
./optiminer-zcash: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

**Comment by Optiminer** [comment]
See https://github.com/Optiminer/OptiminerZcash#libopenclso1-cannot-open-object

**Comment by alexellis** [comment]
How would you install openCL? There are no instructions here
