### ISSUE TITLE
Watchdog Trigger Condition Doesn't Work for Solo Mining

### ISSUE THREAD

**Issue by dlehenky** [Optiminer/OptiminerZcash#30]
Triggering the watchdog based on receipt of shares is actually not all that useful. It doesn't work at all, if you are solo mining. Even on a pool, the choice of watchdog timeout is critical, and not easy for a novice miner to discern, since different pools have different difficulties, including vardiff. It would seem to me that the timeout would be better applied to solutions received from each GPU, rather than shares found on the host-side of the miner, which would remove the significance of the share/block difficulty. Since you are checking solutions against the target on the host, there should be solutions being returned by the GPU for every hash, so if a kernel run doesn't return solutions, there's something wrong, at least the way I understand it. I would wager that miners using the watchdog now are unknowingly exceeding the watchdog timeout when there's nothing actually wrong, other than the variance inherent in finding shares.

**Comment by Optiminer** [comment]
The watchdog is triggered when the GPU does not report any solutions (aka hashes) for the given period of time. So, it works exactly as you describe that it should work.

**Comment by dlehenky** [comment]
Sorry then. Somehow I had come to think it triggered on shares. Reading too many forum posts, I guess :) Btw, v1.5 is running like a rock for me - most stable since v0.6.
