### ISSUE TITLE
0.3.2 hangup/crash when pool/network hiccups  - stratum issue?

### ISSUE THREAD

**Issue by pcollinsca47** [Optiminer/OptiminerZcash#33]
I updated  several machines to 0.3.2, leaving others on 0.3.1. All machines ran for several hours until 4.:57 (machine time) when there was some issue with nicehash and all machines stopped mining. The 0.3.1 machines recovered
(as did cpu miners running nheqminer) but the 0.3.2 machines gave an error message and were not able to recover and continue. These machines had to have the mining script killed by hand and restarted.

All machines where started via the command:
  screen -dmS optiminer bash -c "while true; do ./startoptiminer.sh; done"

It is likely that the problem was revealed by a network problem as all miners at this site saw a problem at the same time, while those at  another site with an independent network connection did not.

![screen shot 2016-11-15 at 4 27 40 am](https://cloud.githubusercontent.com/assets/7938058/20304964/48a27936-aaf0-11e6-85a3-2a35549a6953.png)

(if screen shot doesn't appear, the final message was:

...INFO [GPU0]...
...ERROR [default] Failed to send Message!
...ERROR [stratum] IO/Error communicationg to equihash.usa.nicehash.com

At this point the world stops for these miners. 

)

**Comment by Optiminer** [comment]
Will be fixed in next release.

**Comment by Optiminer** [comment]
Fixed release 0.3.4.
