### ISSUE TITLE
Reliable crash during the first minute

### ISSUE THREAD

**Issue by VoLaHiLaOliBa** [Optiminer/OptiminerZcash#34]
Hi All.
I'm also very interested to get that Optiminer beast running (my admiration by the way for these Sol-rates!), but I do get reliable crashes during the first minute after starting.
Everything looks well, the log looks good, the hash rates look awesome (like shown/reported by the others), nothing unnormal.
But during the first minute after starting, the machine black-screen's and reboots.
No infos, no log, nothing.

In contrast, SA runs fine without any issues.

I'm with 3 * RX480 @ Debian 8.x, partly stable, partly testing.
I already tested 0.31, 0.32 and 0.33 with Kernel 4.7.0 (bpo) and 4.8.0-1 as well as amdgpu-pro driver 16.30 and/or 16.40. All are working but crashing during the first minute.

Any idea?

**Comment by Optiminer** [comment]
Probably a problem with power supply. You can use atiweak -p to reduce power usage if the system cannot handle the full load.

**Comment by VoLaHiLaOliBa** [comment]
You're right!
Couldn't believe it while I read your answer cause I already noticed that SA runs without problems^^.
I also have an powermeter on my miners power line (at wall) and it showed me approx 15-20W less than with SA, but seems like Optiminer produces higher peaks which probably don't get shown on my cheap powermeter.
However, runs now without any problems with one and two cards. As soon as I add the third one it takes a couple of seconds till it restarts.

Thanks a lot for your help!!
