### ISSUE TITLE
improve speed

### ISSUE THREAD

**Issue by nerdralph** [Optiminer/OptiminerZcash#37]
Claymore v6 gets 145 sol/s on a Rx 470 clocked at 1250/1750.  Optiminer should be able to get up to 225 sols/s or ~200 sols + 10% dev fee.
https://bitcointalk.org/index.php?topic=1679855.0

**Comment by Optiminer** [comment]
Hash speed improvements are a continuous goal.

Note that you will never fully reach the memory transfer rates as specified for the cards in a practical algorithm like equihash.
