### ISSUE TITLE
How install OptiminerZcash

### ISSUE THREAD

**Issue by pcd70** [Optiminer/OptiminerZcash#4]
I would like to install Optiminer for linux. How is it works ?
I am not able to download something of executable

Thank's

**Comment by ngonzal** [comment]
Some idiot tried selling a way to circumvent the dev fee.  So the Optiminer developer has pulled all binaries.  Optiminer doesn't seem to be an option anymore unfortunately.

**Comment by Optiminer** [comment]
Download is available again.
