### ISSUE TITLE
GPU dying handling

### ISSUE THREAD

**Issue by hackmyl1fe** [Optiminer/OptiminerZcash#40]
Is there a way to handle GPU stopping?

I am having an issue where after a while one of the GPUs will simply stop reporting. There will be no accepted shares or no stats (sol/s) in the logs.
Currently I am running a cron job every minute checking the last 50 lines of the logs created by Optiminer. When the script cannot find at least one line for all the GPUs it tries to restart the process. But every time i do a `kill` or `kill -9` on said process ubuntu crashes and i must manually reboot the box. 

Is there a better way i should kill the running process? Should i send a different signal?

**Comment by MartinMakowski** [comment]
Hackmyl1fe,

You may have a hardware issue.

After the GPU stops running execute the following command and post us the "red" section of the last logs:
dmesg

If there are hardware exceptions that would explain the need for a hard boot.

- Marty

**Comment by mifa** [comment]
I have same problem with one of my 3 GPUs VTX3D r9 390, 2 of them already dead, so I am sure something wrong with hardware.

**Comment by mifa** [comment]
I found oil dripped from cards to usb riser, I replace one and put litter, it works like a charm now :smiley:

**Comment by hackmyl1fe** [comment]
Hi Marty,

Here is what I found after all the boot related stuff 
`[13059.793031] perf interrupt took too long (2525 > 2500), lowering kernel.perf_event_max_sample_rate to 50000`
