### ISSUE TITLE
GPU Miner does not show temp and fan of GPU1 .. only show it for GPU0 ... otherwise the application works great!

### ISSUE THREAD

**Issue by sweetpuff** [Optiminer/OptiminerZcash#44]
1. Make sure that your problem is reproducible.

Does it still happen after a reboot? -yes
Is it related to some local problem,-no  
 e.g., is your internet connection working?-yes
2. Collect as much information as possible.
Add at least following information to the bug report:
    Which OS are you using? Windows 10 Home.
    Which version of the miner are you using - AMD GPU Miner v12.1 Beta - Catalyst 15.12-16.12
    Which graphic driver are you using- Radeon RX 480 graphics ... 10/02/2017-21.19.519.2
    What GPUs are you using Radeon RX 480 & 470's  . 
    How often is this problem happening? Everytime
    What is the expected behavior and what is the actual behavior.
The GPU Miner only shows GPU0's temp and fan every 30 seconds or whatever ... It does not show GPU1 .... I am running 3 rigs with two GPU's in each
    Try different settings:
        Does changing the intensity make any difference (-i).-no
        If you have multiple GPUs just run on one (-d). -yes Also try to remove GPUs from the system.-tried that
        Try a different mining pool.I can't get suprnova to give my login back .... can't get onto another pool
    Enable logging (--log-file) and attach log file when reporting the bug.

3. Open an issue.

If you have followed step 1 and 2 you are ready to open a new Issue here: https://github.com/Optiminer/OptiminerZcash/issues/new

[1490193466_log.txt](https://github.com/Optiminer/OptiminerZcash/files/862085/1490193466_log.txt)

**Comment by Optiminer** [comment]
Your log shows you are using claymore not optiminer.
