### ISSUE TITLE
Linux Rig freezes or reboots w/ v0.5.0

### ISSUE THREAD

**Issue by WoK-E** [Optiminer/OptiminerZcash#45]
Ubuntu 16.04.1 Desktop, AMDGPU-PRO
Intel Pentium G3258, 4GB RAM
3 x ASUS R9-380X-O4G-GAMING

Rigs with R9 380, RX470, and RX480 working fine, 5% sol/s increase compared to v0.4.0

**Comment by Optiminer** [comment]
Have you tried different values for -i? Do you use risers?

**Comment by WoK-E** [comment]
Yes, I've tried values from -i 4 (autodetected) down to -i 1 - Same behaviour
One card in on mobo, the other 2 on USB risers - Risers do not seem to be the problem, as they work fine with v0.4.0, and I also exchanged them with others from a rig that works fine with v0.5.0

**Comment by WoK-E** [comment]
Still crashing w/ v0.6.0 - Removed and re-seated the cards and risers a few times, and now it works fine
Does not seem to be a software problem
Closing issue
