### ISSUE TITLE
Any recourse for honest/loyal miners?

### ISSUE THREAD

**Issue by outragedhuman** [Optiminer/OptiminerZcash#5]
Just wondering if there's any recourse for those of us who never circumvented the fee controls in place. I've been running your miner since you passed up mbevand's miner, long ago, and have never disabled your fees. 

Any chance we can continue to use your miner?

**Comment by Optiminer** [comment]
Sure, you can continue to use my miner if you agree with the dev fee. You can get the latest private version from https://www.dropbox.com/s/4tzxmcx8aa901zj/optiminer-zcash-0.9.1.tar.gz?dl=0

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

7. Dec 2016 04:21 by notifications@github.com:

**Comment by outragedhuman** [comment]
Many thanks Optiminer, thanks for writing an awesome miner!
