### ISSUE TITLE
No way to specify OpenCL Platform

### ISSUE THREAD

**Issue by lhl** [Optiminer/OptiminerZcash#5]
My GPU is enumerated on the second OpenCL platform, and even trying different IDs with the `-d` flag, I get the following error:

```
ERROR [default] OpenCL error: cl::Context::Context() (-1)
```

For reference, here's what silentarmy's `--list` enumrates:

```
Devices on platform "AMD Accelerated Parallel Processing":
  ID 0: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Devices on platform "AMD Accelerated Parallel Processing":
  ID 1: Ellesmere
  ID 2: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
```

**Comment by rbrtio** [comment]
It looks like "-c" specifies the platform and "-d" specifies the device.  Did you try with -c 1 ?

> -d <integer>,  --device <integer>  (accepted multiple times)
     A OpenCL device id to use. If no devices are specified, all are used.

> -c <integer>,  --platform <integer>
     The OpenCL platform id to use.

**Comment by lhl** [comment]
Ah, yeah, that seems to do it, must have missed that, thanks @rbrtio
