### ISSUE TITLE
1.7.0: [error] Required argument 'stratum' is missing!

### ISSUE THREAD

**Issue by Allmentux** [Optiminer/OptiminerZcash#52]
Optiminer fails to start because of this:

```
~/Downloads/optiminer-zcash$ ./optiminer-zcash 
[2017-06-27 00:05:05.606] [info] Optiminer/Zcash 1.7.0 (C) Optiminer 2017
[2017-06-27 00:05:05.607] [error] Required argument 'stratum' is missing!

```

My mine.sh file:

```
export GPU_FORCE_64BIT_PTR=1

POOL=zstratum+tls://eu1-zcash.flypool.org:3443
USER=zhas-adress.name
PASSWORD=x

cd "$(dirname "$0")"
while true
do
  ./optiminer-zcash -s $POOL -u $USER -p $PASSWORD --watchdog-timeout 30 --watchdog-cmd "./watchdog-cmd.sh"
  if [ $? -eq 134 ]
  then
    break
  fi
done

```

I dont see where I could have made a config-error which causes the "stratum is missing" error.
Any idea why this happens? Nobody else seems to have that problem.. at least google does not show anything in that direction :(

**Comment by Optiminer** [comment]
You need to start the mine.sh not optiminer-zcash directly:$ sh mine.sh

Happy mining!

27. Jun 2017 00:10 by notifications@github.com:

**Comment by Allmentux** [comment]
Stupid me...  now it works! 

Maybe you can emphasize it in the tutorial, so people also try to run "sh mine.sh".
From what I understood from your tutorial, users should run "./optiminer-zcash".
