### ISSUE TITLE
Only averaging 22.72 h/s - HELP 

### ISSUE THREAD

**Issue by Maximellian** [Optiminer/OptiminerZcash#53]
Hi - I am new to using the Optiminer for Zcash GPU mining.  I am running Windows 7 - 64 bit with AMD Radeon R5 240 using the suggested 15.12 drivers.  From what I have read on the forums an average of 22.72 h/s seems quiet low.  Below are the details of 'start.bat'.  Of course replaced my User/PW with XYZ in the below text.  Any help would be appreciated.

REM Flypool setup:
SET POOL=zstratum+tls://eu1-zcash.flypool.org:3443
SET USER=XYZ.worker
SET PASSWORD=XYZ

REM For nicehash uncomment following (uses bitcoin address as user):
REM POOL=equihash.usa.nicehash.com:3357
REM USER=19STEagfLfbb1XdTF9NCf5kmxZHGchSiZj
REM PASSWORD=x

REM For suprnova.cc use following:
REM POOL=zec.suprnova.cc:2142
REM USER=Weblogin.Worker
REM PASSWORD=WorkerPassword

SET GPU_FORCE_64BIT_PTR=1

optiminer -s %POOL% -u XYZ -p XYZ -m 8080

pause

**Comment by Maximellian** [comment]
Also - on startup it says "failed to list devices on platform"

**Comment by Optiminer** [comment]
What does output does optiminer --list-devices give? Please post it here.

The R5 240 is a 4 year old card which has only 28.8 GB/s memory bandwidth. This is only 1/10th of a mondern card, so, 22.7H/s does not sound completely off. Also try with different values for "-i"

I just tested again my R7 240 again. It gives about 35 H/s under linux. I'd expect the R5 240 to have the same performance but I there might be difference between the cards I am not aware of. Of course, you could try running under linux to see if it makes a difference.

For the reference, here is the output of clpeak for the R7 240 (dunno if there is a windows build for clpeak)
$ ./clpeak 

Platform: AMD Accelerated Parallel Processing
  Device: Oland
    Driver version  : 1912.5 (VM) (Linux x64)
    Compute units   : 5
    Clock frequency : 780 MHz

    Global memory bandwidth (GBPS)
      float   : 23.83
      float2  : 24.71
      float4  : 25.33
      float8  : 13.17
      float16 : 6.80

    Single-precision compute (GFLOPS)
      float   : 494.42
      float2  : 481.71
      float4  : 480.97
      float8  : 479.32
      float16 : 464.25

    No half precision support! Skipped

    Double-precision compute (GFLOPS)
      double   : 31.17
      double2  : 31.15
      double4  : 31.12
      double8  : 31.05
      double16 : 30.92

    Integer compute (GIOPS)
      int   : 99.66
      int2  : 99.65
      int4  : 99.63
      int8  : 99.59
      int16 : 99.52

**Comment by Maximellian** [comment]
Thanks for the input!  I know the video card is a bit... hmmm... dated.  I used to have a nice large desktop tower which fit 2-4 video cards, but that was destroyed in a flood.  Now I have a super compact unit with 1-slim profile video card.  Below is the output right after starting Optiminer.  

This is the one error I see popping up:
[2017-07-03 17:51:38.729] [warning] Failed to list devices of platform 0: "CL_DE
VICE_NOT_FOUND" Ignoring this platform.

In regards to intensity.  Anything about 0-1 the H/s start to drop off.  At 6 the computer starts to lag a bit.

--------------------------------------------------------------------------------------------------------------

C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>ECHO "Change th
e user and password in start.bat to yours!"
"Change the user and password in start.bat to yours!"
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM Flypool set
up:
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>SET POOL=zstrat
um+tls://eu1-zcash.flypool.org:3443
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>SET USER=xyz.worker
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>SET PASSWORD=xyz
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM For nicehas
h uncomment following (uses bitcoin address as user):
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM POOL=equiha
sh.usa.nicehash.com:3357
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM USER=19STEa
gfLfbb1XdTF9NCf5kmxZHGchSiZj
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM PASSWORD=x
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM For suprnov
a.cc use following:
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM POOL=zec.su
prnova.cc:2142
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM USER=Weblog
in.Worker

C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>REM PASSWORD=Wo
rkerPassword
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>SET GPU_FORCE_6
4BIT_PTR=1
C:\Users\\Downloads\optiminer-zcash-1.7.0\optiminer-zcash-win>optiminer -s zs
tratum+tls://eu1-zcash.flypool.org:3443 -u xyz -
p xyz -m 8080 -i 1
[2017-07-03 17:51:38.244] [info] Optiminer/Zcash 1.7.0 (C) Optiminer 2017
[2017-07-03 17:51:38.248] [info] Connecting to eu1-zcash.flypool.org:3443.
[2017-07-03 17:51:38.729] [warning] Failed to list devices of platform 0: "CL_DE
VICE_NOT_FOUND" Ignoring this platform.
[2017-07-03 17:51:39.298] [info] Using highly optimized kernel code for Oland de
vices.
[2017-07-03 17:51:39.301] [info] Using '--intensity 1' from command line for dev
ice 0.
[2017-07-03 17:51:39.340] [info] [GPU0] Device info: {"id": "1/0" "name": "Oland
" "platform": "AMD" "driver": "1912.5 (VM)"}
[2017-07-03 17:51:39.572] [info] GPU0 Waiting for work from pool.
[2017-07-03 17:51:39.575] [info] TLS handshake with eu1-zcash.flypool.org succee
ded.
[2017-07-03 17:51:39.709] [info] Extranonce is '05b143f006'.
[2017-07-03 17:51:39.843] [info] Connected to eu1-zcash.flypool.org:3443.
[2017-07-03 17:51:39.843] [info] Mining target is 00083126e978d4fdf3b645a1cac083
126e978d4fdf3b645a1cac083126e978d4
[2017-07-03 17:51:40.843] [info] Got new work.
[2017-07-03 17:51:40.845] [info] GPU0 Got work, start mining.
[2017-07-03 17:51:45.979] [info] [GPU0]  12.6 I/s 22.4 S/s (5s)
[2017-07-03 17:51:48.289] [info] [Total]  12.4 I/s 24.4 S/s (5s)
[2017-07-03 17:51:51.050] [info] [GPU0]  12.4 I/s 24.6 S/s (5s)
[2017-07-03 17:51:53.311] [info] [Total]  12.6 I/s 23.2 S/s (5s)

**Comment by Maximellian** [comment]
At an average of 24.2 overall.  There is still the "Failed to list devices of platform 0: "CL_DE" error but seems stable enough.  Never crashes!  I have intensity = 0 (-i 0).

If you have any other thoughts on how I can better optimize the current worker setup - or how to fix the error please let me know!

Thanks again!  Once I receive my first payout I'll be sending you a donation (tiny but something for now).

**Comment by Optiminer** [comment]
I do not think there is more possible with this card, sorry!

"The failed list devices on platform 0" warning is no problem. It just means you have a another OpenCL driver installed which does not have any GPU associated with. As your GPU is found on the other platform you are fine.
