### ISSUE TITLE
[error] OpenCL error: Failed to read bin/asm.bin (CL_DEVICE_NOT_FOUND)

### ISSUE THREAD

**Issue by calvintam236** [Optiminer/OptiminerZcash#57]
```
[error] OpenCL error: Failed to read bin/asm.bin (CL_DEVICE_NOT_FOUND)
```

Using the binary on release. Any idea how to fix it?

**Comment by Optiminer** [comment]
Start the miner using the given scripts.

It must be run from the directory where the binary is located.
