### ISSUE TITLE
Poor performance from R9 380's

### ISSUE THREAD

**Issue by scavern** [Optiminer/OptiminerZcash#6]
I'm seeing really bad numbers on R9 380's... looking at 16 S/s.

**Comment by Optiminer** [comment]
What driver do you use? Have you tried lowering the intensity?

**Comment by scavern** [comment]
Driver is fglrx 15.20.3. Intensity is set at 3.

**Comment by Optiminer** [comment]
Do you have other things running on the X server? Try closing everything else.

**Comment by bpvarsity** [comment]
I'm seeing the normal 100-112. Not sure what your issue is but it's not opti.

**Comment by scavern** [comment]
Managed to resolve issue. Getting about 140 per gpu. Not sure if that is correct for r9 380?
