### ISSUE TITLE
is there a dev fee ?

### ISSUE THREAD

**Issue by MathieuVachon** [Optiminer/OptiminerZcash#6]
in the title ...

**Comment by rbrtio** [comment]
A dev fee was mentioned by the dev on both BitCoinTalk and the Zcash forum, but to my knowledge it was not specified how much.

The statistics as displayed by the miner take the dev fee into account, so what the client outputs is what YOU are receiving.  I have validated this by checking my pool statistics and they match what the miner says.

I hope that helps...

**Comment by Optiminer** [comment]
Yes, there is a dev fee. Some GPU time is used to mine for the dev. All shown rates are 'net' that is with dev fee deducted. So, it is you get what you see.

**Comment by MathieuVachon** [comment]
perfecto. Anyways , not gonna complain, its faster than anything I used on 'nix.
