### ISSUE TITLE
Found no matching devices: Possible reason and solution?

### ISSUE THREAD

**Issue by Blackbam1337** [Optiminer/OptiminerZcash#60]
Hey there I am pretty new to this topic therefore sorry if this is a noob question. I have running ArchLinux and have installed opencl-mesa:

`sudo pacman -S opencl-mesa`

If I am trying to run Optiminer I end up with the following errors:

`./optiminer-zcash -s eu1-zcash.flypool.org:3333 -u ......`

[2017-08-29 15:48:37.637] [info] Optiminer/Zcash 1.7.0 (C) Optiminer 2017
[2017-08-29 15:48:37.638] [info] Connecting to eu1-zcash.flypool.org:3333.
[2017-08-29 15:48:37.733] [error] Found no matching devices! Quitting!

`./optiminer-zcash --list-devices`

[2017-08-29 16:01:03.132] [info] Optiminer/Zcash 1.7.0 (C) Optiminer 2017
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: Unknown
  Device Name: AMD CEDAR (DRM 2.50.0 / 4.12.8-2-ARCH, LLVM 4.0.1)
  Driver Version: 17.1.7
  Address bits: 32
  Available memory: 214588832

Is this a bug, not supported or a configuration issue and how may it be solved?

**Comment by Optiminer** [comment]
What GPU do you have? It might just be too old to be supported.
You might also want to try a different opencl driver, see https://wiki.archlinux.org/index.php/GPGPU#AMD.2FATI

**Comment by Optiminer** [comment]
Platform Vendor: **Unknown**

Don't know why it shows up as unknown, this should say AMD. Try with a different opencl driver.

**Comment by Optiminer** [comment]
Using amdgpu with mesa is not supported. Install opencl from amdgpu-pro:
https://wiki.archlinux.org/index.php/AMDGPU#AMDGPU_PRO

For older devices (pre rx470), it is even better to use fglrx driver instead.
