### ISSUE TITLE
Is Your Devfee Proxy Running?

### ISSUE THREAD

**Issue by dlehenky** [Optiminer/OptiminerZcash#62]
Hi Opti. After many months running v1.7, I'm suddenly (today) seeing a consistent raw sols/sec drop on *every* GPU (122 * Nano) of ~12 sols/s. Is your proxy down? Changed the proxy IP address? It *seems* as though I'm getting the "no devfee" hash rate, even though I'm not using that option. I can't think of any other reason why my sols/s would drop like it has. Please help!

**Comment by dlehenky** [comment]
More Info: I can ping your proxy, and I checked the DNS host name for the IP address, so I know nothing has changed, in that regard. So, I took my 1 GPU dev rig and added the '--nodevfee' miner option and restarted the miner. I confirmed that I am getting the same hash rate on all my rigs, regardless of the '--nodevfee' option being on or off. Your devfee proxy must be down/broken. Given that I'm giving up the devfee percentage now, as well as you, could you get the proxy back up, please?

**Comment by dlehenky** [comment]
More: The hash drop started at ~10 PM Friday night local time (GMT -6).

**Comment by dlehenky** [comment]
Well, it came back to normal for about 6 hours during the morning hours, my time, then back down again, as it remains currently. This really sucks, to be honest.

**Comment by dlehenky** [comment]
One more thing: I had never seen this problem before, but the problem started after flypool raised the pool difficulty from 8000 to 16000. The average time to find a share is now 36 seconds or so. I have no idea if that might mess up your devfee share algo or what not. Just thought I'd let you know. :)

**Comment by Optiminer** [comment]
Restarted the proxy. Should be okay again now.

**Comment by dlehenky** [comment]
Thank you!
