### ISSUE TITLE
Titan Xp

### ISSUE THREAD

**Issue by g01dt00th** [Optiminer/OptiminerZcash#63]
Hello!

My rig with 6x GTX Titan Xp not started more than 4 GPUs. Optminer process load is 92-98% of CPU time.

Working correctly only with 3 GPUs (-d 0 -d 1 -d 2) and only one process! I try to start second process with -d 3 -d 4 -d 5 - second miner was crash immediately.

**Comment by Optiminer** [comment]
OptiminerZcash does not support NVIDIA cards yet.
