### ISSUE TITLE
ERROR [default] OpenCL error

### ISSUE THREAD

**Issue by Ajworry** [Optiminer/OptiminerZcash#7]
ERROR [default] OpenCL error: cl::Context::Context() (-1) ?

Ubuntu 15.04, flgrx 15.302

**Comment by Optiminer** [comment]
Do you have opencl installed properly?

**Comment by Ajworry** [comment]
i install sudo ./AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.sh
SA normal work

**Comment by Optiminer** [comment]
Try running clinfo as the same user. You may need to run the miner as root if the user does not have the permissions to access graphic card.

**Comment by Ajworry** [comment]
bill@server4:~/mining/optiminer-zcash$ sudo ln -s /usr/lib/libOpenCL.so /usr/lib/libOpenCL.so.1
ln: failed to create symbolic link ‘/usr/lib/libOpenCL.so.1’: File exists
bill@server4:~/mining/optiminer-zcash$ sudo ./optiminer-zcash -s eu1-zcash.flypool.org:3333 -u xxxx.server4 -p z
No protocol specified
No protocol specified
2016-11-15 13:04:17,845 ERROR [default] OpenCL error: cl::Context::Context() (-1)

**Comment by Ajworry** [comment]
bill@server4:~$ locate libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86/libOpenCL.so.1
/opt/AMDAPPSDK-3.0/lib/x86_64/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libOpenCL.so
/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/libOpenCL.so.1
/usr/lib/libOpenCL.so
/usr/lib/libOpenCL.so.1
/usr/lib/i386-linux-gnu/libOpenCL.so.1

**Comment by Ajworry** [comment]
fresh install on 14.04 and works
