### ISSUE TITLE
miner contains a 2.5% fee - IP HOST 

### ISSUE THREAD

**Issue by fmin09er** [Optiminer/OptiminerZcash#70]
hi i have one question about optiminer windows ver i downloaded and testing im not programer for the long time but im system admin and i have one question about where this miner connect to to mine for fee because i dont mind that developer whants to get somthing from his work but i will make some changes to firewall so it connects only to some pools, i make some quick analyse and i see that if i run optiminer that hi goes to two diffrent address first one is my pool but second is on: 
 **Optiminer.exe	5836	TCP	mypc-test	49970	static.25.30.99.88.clients.your-server.de	4043	ESTABLISHED			72	23.688**		

if this is dev server then ok if not then all that use windows exe has one hidden process thats connects to host that i mention below, i havent tested linux ver so i cant say its the same

hope we get feedback from dev about this issue

**Comment by Optiminer** [comment]
The miner connects to the host proxy.optiminer.pl which currently resolves to the ip 88.99.30.25. But it is better to whitelist the host name in the firewall as the ip might change over time.

If you block the connection to the dev fee server, the miner will run in the slower nodevfee mode (same as '--nodevfee').

Hope this answers your questions.

**Comment by fmin09er** [comment]
mate,
thnx for answer, no i dont have nothing against dev fee, i know that you had to invest time and effort to make this program so if i get somthing from it why you should not :), i had only to know that i have clean not tainted with (trojan, spyware) so its ok, i have you program that is running on AMD R9 380 and is performing 180 sol/s i tested allmost all other miners and yours is fastest of all others so good job mate, i have another question do you plan to include NVidia cards because most of my cards are NVidia and i run it on windows so can we expect windows release for nividia cards

best wishes,
f

**Comment by Optiminer** [comment]
I hope I can support NVidia cards at a competitive speed with other miners in the future. But I do not have any ETA for that. Right now, you could consider mining Zero or Minex with
https://github.com/Optiminer/OptiminerEquihash
