### ISSUE TITLE
GPU Faults

### ISSUE THREAD

**Issue by rbrtio** [Optiminer/OptiminerZcash#8]
In reviewing the output of dmesg I discovered multiple GPU Fault entries.  Thus far the application continues to run, but I thought you should be aware.

[ 2054.682462] amdgpu 0000:05:00.0: GPU fault detected: 147 0x09f8c401
[ 2054.686537] amdgpu 0000:05:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x04102F3F
[ 2054.690624] amdgpu 0000:05:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x080C4001
[ 2054.694712] VM fault (0x01, vmid 4) at page 68169535, read from 'TC3' (0x54433300) (196)

**Comment by rbrtio** [comment]
I forgot to mention that these appear for all GPUs in the system from time to time even with the mclk set to the factory speed of 1650MHz.

**Comment by Optiminer** [comment]
Thanks for reporting. It is rare enough that it does not affect mining but will try to find where that happens.

**Comment by Karasur** [comment]
The same problem, on some system miner crashes (have to reboot system), with others it continue to mine but without crashed gpus.

**Comment by osnwt** [comment]
Not rare, I would say. Same issue with 470 Nitro+ 8GB (Samsung memory), 4G (Hynix), 4GB (Elpida). It  doesn not affect mining, but in the end one card in my rig stopped mining and did not show stats anymore for that GPU, total was lower and miner said nothing in logs at all. Not a good sign.

**Comment by Optiminer** [comment]
It is not clear that the crashes / freezes you have seen are related to the errors in shown in the system log. I intend to implement a watchdog that triggers if a card does not return any solution for X seconds.

**Comment by Karasur** [comment]
May be the problem in bad risers, memory intensive data corrupts and gpu hangs.
all my rigs with amd-pro driver have such errors but only some of them have problem with gpu.
Flashing to stock bios (elpida memory) helps with one rig, other rig with stock furyx has a problem with 1 gpu.

**Comment by rbrtio** [comment]
Just to add some data, I can run my systems on Windows mining for over 12 hours without dropping a GPU and I can't do that with Linux.

In this example, I used SA since it is available on both platforms.

This would lead me to think it is driver related unfortunately as Linux is my preference.

**Comment by Optiminer** [comment]
GPU fault entries are fixed in v0.3.3.
